Repository ros-infrastructure/vcs2l, pull requests merged in 2025-09, with the labels that each got.

#64 Bump minimum Python version to 3.6
  README.md
  setup.py
  stdeb.cfg
  vcs2l/errors.py
Labels: bug

#65 Fix dependency for entry_points import
  README.md
  setup.py
  stdeb.cfg
Labels: bug, dependencies

#55 Added release playbook for project deployment.
  release_playbook.md
Labels: documentation

#73 Fix python version requirement in setup.py
  setup.py
Labels: bug
